### ISSUE TITLE
Folders not being created; chdir fails

### ISSUE THREAD

**Issue by msarahan** [vito/houdini#10]
I have this pipeline:

```
jobs:
  - name: job-collect-tasks
    public: true
    serial: true
    plan:
      - task: generate-tasks
        config:
          platform: linux32
          run:
            path: echo
            args: 
              - weeee
```

I've successfully registered a houdini server and a baggageclaim server on my worker, as I described in https://github.com/concourse/concourse/issues/1547

If I run that pipeline, it fails with:

```
hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"chdir /usr/local/concourse_worker/containers/00002al7rgv/tmp/build/fb696a99: no such file or directory","Handle":""}
```

I am running houdini and baggageclaim with these arguments:

```
nohup ./houdini -depot=./containers &
nohup ./baggageclaim --driver=naive --volumes=./volumes &
```

Inspecting the worker, it does appear that /usr/local/concourse_worker/containers/00002al7rgv exists, but the other folders do not.  What do I need to do to get houdini or anything else to create those folders?
